/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import DB.DBConnection;

import com.sun.glass.events.MouseEvent;
import com.sun.javafx.embed.AbstractEvents;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static java.lang.ProcessBuilder.Redirect.to;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author DELL
 */
public class hangman extends javax.swing.JFrame {

    DBConnection obj = new DBConnection();
    Object selid;
    public int qn = 1, p = 0, life = 4;
    public String qtn, op1, op2, ans, pt, rsans, val;

    /**
     * Creates new form hangman
     */
    public void query() {

        //make it a function
        btn_next.setVisible(false);
        txt_ans.setText("");
        String qus = "";
        String lstid = "";
   

        try {
            qus = "Select * from tbl_questionbank order by rand() limit 1";
            ResultSet rs = obj.SelectData(qus);

            if (rs.next()) {

                qtn = rs.getString("qus_name");
                txt_qus.setText(qtn);
                op1 = rs.getString("op1");
                txt_op1.setText(op1);
                op2 = rs.getString("op2");
                txt_op2.setText(op2);
                ans = rs.getString("ans");

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }

    public hangman() {
        initComponents();

        JOptionPane.showMessageDialog(this, "Welcome to the Hangman Game.\n The game is about a man who is meant to be hanged keep him alive as long as possible by answering the right question. \n Rules\n1.You have 4 lifes\n2.Enter the right option number in the box given\n\n Best of luck");
        setSize(800, 600);
        setResizable(false);
        //   btn_next.setVisible(false);
        lbl_op1.setVisible(true);
        lbl_op2.setVisible(true);
        lbl_p1.setVisible(true);
        lbl_p2.setVisible(false);
        lbl_post1.setVisible(false);
        lbl_post2.setVisible(false);
        lbl_ans.setVisible(true);
        lbl_rp.setVisible(false);
        lbl_x.setVisible(false);
        txt_op1.setVisible(true);
        txt_op2.setVisible(true);
        txt_qn.setVisible(true);
        txt_qus.setVisible(true);
        txt_ans.setVisible(true);
        btn_back.setVisible(true);
        btn_next.setVisible(false);

        txt_qn.setText("Q : 1");
        txt_lifes.setText("4");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        txt_ans = new javax.swing.JTextField();
        lbl_ans = new javax.swing.JLabel();
        txt_op2 = new javax.swing.JTextField();
        txt_op1 = new javax.swing.JTextField();
        lbl_op2 = new javax.swing.JLabel();
        lbl_op1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pts = new javax.swing.JTextField();
        txt_lifes = new javax.swing.JTextField();
        txt_qus = new javax.swing.JTextField();
        txt_qn = new javax.swing.JTextField();
        btn_next = new javax.swing.JButton();
        lbl_p2 = new javax.swing.JLabel();
        lbl_p1 = new javax.swing.JLabel();
        lbl_rp = new javax.swing.JLabel();
        lbl_x = new javax.swing.JLabel();
        lbl_post2 = new javax.swing.JLabel();
        lbl_post1 = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(0, 0, 110, 50);

        txt_ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ansActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ans);
        txt_ans.setBounds(90, 340, 270, 30);

        lbl_ans.setText("Answer : ");
        getContentPane().add(lbl_ans);
        lbl_ans.setBounds(20, 340, 70, 30);

        txt_op2.setEditable(false);
        txt_op2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(txt_op2);
        txt_op2.setBounds(60, 410, 300, 27);

        txt_op1.setEditable(false);
        txt_op1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(txt_op1);
        txt_op1.setBounds(60, 380, 300, 27);

        lbl_op2.setText("2)");
        getContentPane().add(lbl_op2);
        lbl_op2.setBounds(30, 410, 20, 30);

        lbl_op1.setText("1)");
        getContentPane().add(lbl_op1);
        lbl_op1.setBounds(30, 380, 20, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Points :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 30, 80, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Lifes : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 80, 70, 24);

        txt_pts.setEditable(false);
        txt_pts.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txt_pts);
        txt_pts.setBounds(630, 30, 100, 40);

        txt_lifes.setEditable(false);
        txt_lifes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txt_lifes);
        txt_lifes.setBounds(630, 80, 100, 40);

        txt_qus.setEditable(false);
        txt_qus.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(txt_qus);
        txt_qus.setBounds(70, 280, 340, 30);

        txt_qn.setEditable(false);
        txt_qn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_qn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qnActionPerformed(evt);
            }
        });
        getContentPane().add(txt_qn);
        txt_qn.setBounds(10, 280, 50, 30);

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        getContentPane().add(btn_next);
        btn_next.setBounds(290, 10, 220, 100);

        lbl_p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/picp2.png"))); // NOI18N
        getContentPane().add(lbl_p2);
        lbl_p2.setBounds(440, 250, 210, 200);

        lbl_p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/picp1.png"))); // NOI18N
        getContentPane().add(lbl_p1);
        lbl_p1.setBounds(440, 320, 210, 200);

        lbl_rp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/picrp.png"))); // NOI18N
        getContentPane().add(lbl_rp);
        lbl_rp.setBounds(390, 200, 180, 200);

        lbl_x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/picx.png"))); // NOI18N
        getContentPane().add(lbl_x);
        lbl_x.setBounds(590, 250, 100, 70);

        lbl_post2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pic2.png"))); // NOI18N
        getContentPane().add(lbl_post2);
        lbl_post2.setBounds(440, 270, 210, 20);

        lbl_post1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pic1.png"))); // NOI18N
        getContentPane().add(lbl_post1);
        lbl_post1.setBounds(620, 250, 20, 230);

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_img.png"))); // NOI18N
        lbl_bg.setDoubleBuffered(true);
        getContentPane().add(lbl_bg);
        lbl_bg.setBounds(0, 0, 800, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        JOptionPane.showMessageDialog(this, "Your game will be lost");

        try {
            String prv = "select player_id from tbl_player order by player_id desc limit 1";
            ResultSet rs = obj.SelectData(prv);

            if (rs.next()) {

                val = rs.getString("player_id");

            }
            System.out.println(val);
            String delete = "delete from tbl_player where player_id=('" + val + "')";
            int a = obj.ExecuteQuery(delete);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_qnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qnActionPerformed


    }//GEN-LAST:event_txt_qnActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed

        txt_qus.setVisible(true);
        txt_ans.setVisible(true);
        txt_op1.setVisible(true);
        txt_op2.setVisible(true);
        txt_qn.setVisible(true);
        lbl_ans.setVisible(true);
        lbl_op1.setVisible(true);
        lbl_op2.setVisible(true);

        qn = qn + 1;
        txt_qn.setText("Q : " + qn);
        txt_pts.setText("" + p);
        query();

    }//GEN-LAST:event_btn_nextActionPerformed

    private void txt_ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ansActionPerformed

        txt_qus.setVisible(false);
        txt_ans.setVisible(false);
        txt_op1.setVisible(false);
        txt_op2.setVisible(false);
        txt_qn.setVisible(false);
        lbl_ans.setVisible(false);
        lbl_op1.setVisible(false);
        lbl_op2.setVisible(false);

        qtn = txt_ans.getText();
        btn_next.setVisible(true);
        pt = txt_ans.getText();
        //txt_pts.setText("pts"+pt+"  ans" +ans);

        if (pt.equals(ans)) {

            p = p + 1;
            txt_pts.setText("" + p);

        } else if (pt != ans) {
            life = life - 1;
            txt_lifes.setText("" + life);
            switch (life) {
                case 3:

                    lbl_post1.setVisible(true);
                    break;
                case 2:

                    lbl_post2.setVisible(true);
                    lbl_x.setVisible(true);
                    break;
                case 1:
                    lbl_rp.setVisible(true);
                    break;
                case 0:
                    lbl_rp.setVisible(false);
                    lbl_p1.setVisible(false);
                    lbl_p2.setVisible(true);

                    String score = txt_pts.getText();

                    try {
                        String prv = "select player_id from tbl_player order by player_id desc limit 1";
                        ResultSet rs = obj.SelectData(prv);

                        if (rs.next()) {

                            val = rs.getString("player_id");

                        }
                    } catch (Exception e) {

                        JOptionPane.showMessageDialog(null, e);
                    }

                    String insert = "update tbl_player set player_score = '" + score + "' where player_id = '" + val + "' ";
                    int a = obj.ExecuteQuery(insert);

                    JOptionPane.showMessageDialog(this, "GAME OVER");
                    Highscore hi = new Highscore();
                    this.setVisible(false);
                    hi.setVisible(true);
                    break;

            }
        }
    }//GEN-LAST:event_txt_ansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_ans;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_op1;
    private javax.swing.JLabel lbl_op2;
    private javax.swing.JLabel lbl_p1;
    private javax.swing.JLabel lbl_p2;
    private javax.swing.JLabel lbl_post1;
    private javax.swing.JLabel lbl_post2;
    private javax.swing.JLabel lbl_rp;
    private javax.swing.JLabel lbl_x;
    private javax.swing.JTextField txt_ans;
    private javax.swing.JTextField txt_lifes;
    private javax.swing.JTextField txt_op1;
    private javax.swing.JTextField txt_op2;
    private javax.swing.JTextField txt_pts;
    private javax.swing.JTextField txt_qn;
    private javax.swing.JTextField txt_qus;
    // End of variables declaration//GEN-END:variables
}
