/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import DB.DBConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alan
 */
public class Highscore extends javax.swing.JFrame {

    DBConnection obj = new DBConnection();
    Object selid;
    int flag = 0;

    /**
     * Creates new form Highscore
     */
    public Highscore() {
        initComponents();
        setSize(800, 600);
        setResizable(false);
        filldata();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_highscore = new javax.swing.JTable();
        lbl_ctext = new javax.swing.JLabel();
        lbl_cscore = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tbl_highscore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "no", "Username", "Highcsore"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_highscore.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_highscore.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_highscore);
        if (tbl_highscore.getColumnModel().getColumnCount() > 0) {
            tbl_highscore.getColumnModel().getColumn(0).setResizable(false);
            tbl_highscore.getColumnModel().getColumn(1).setResizable(false);
            tbl_highscore.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 730, 190);

        lbl_ctext.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_ctext.setForeground(new java.awt.Color(255, 102, 255));
        lbl_ctext.setText("Current score :");
        getContentPane().add(lbl_ctext);
        lbl_ctext.setBounds(330, 0, 220, 60);

        lbl_cscore.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        lbl_cscore.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(lbl_cscore);
        lbl_cscore.setBounds(370, 40, 210, 110);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backm.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(450, 430, 150, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dead.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 130, 580, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_img.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 860, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void filldata() {
        try {
            int i = 0;
            String heading[] = new String[4];
            heading[0] = "no";
            heading[1] = "sl no";
            heading[2] = "Username";
            heading[3] = "Highscore";

            String sel = "select * from tbl_player order by player_score desc";

            ResultSet rs = obj.SelectData(sel);
            rs.last();
            int row = rs.getRow();
            String data[][] = new String[row][4];
            rs.beforeFirst();
            while (rs.next()) {
                data[i][0] = String.valueOf(i + 1);
                data[i][1] = String.valueOf(i + 1);
                data[i][2] = rs.getString("player_name");
                data[i][3] = rs.getString("player_score");

                i++;
            }
            DefaultTableModel model = new DefaultTableModel(data, heading);
            tbl_highscore.setModel(model);
            tbl_highscore.getColumn("no").setMinWidth(0);
            tbl_highscore.getColumn("no").setMaxWidth(0);
        } catch (SQLException ex) {
            Logger.getLogger(Highscore.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            String prv = "select player_score from tbl_player order by player_id desc limit 1";
            ResultSet hi = obj.SelectData(prv);

            if (hi.next()) {

                String val = hi.getString("player_score");
                lbl_cscore.setText(val);
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        Mainmenu mm = new Mainmenu();
        mm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Highscore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cscore;
    private javax.swing.JLabel lbl_ctext;
    private javax.swing.JTable tbl_highscore;
    // End of variables declaration//GEN-END:variables
}
