/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import DB.DBConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alan
 */
public class Login extends javax.swing.JFrame {

    DBConnection obj = new DBConnection();
    Object selid;
    int flag = 0;
    String passcheck = "";
    String usrcheck = "", username = "";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(800, 600);
        setResizable(false);

        btn_admin.setVisible(true);
        btn_user.setVisible(true);
        lbl_username.setVisible(false);
        txt_username.setVisible(false);
        lbl_psswd.setVisible(false);
        txt_psswd.setVisible(false);
        btn_login.setVisible(false);
        btn_cancel.setVisible(false);
        lbl_m_user.setVisible(false);
        lbl_inst.setVisible(false);
        txt_c_user.setVisible(false);
        btn_login.setEnabled(false);
        //btn_add.setEnabled(false);
        btn_add.setVisible(false);
        btn_cancel1.setVisible(false);
        btn_back.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_add = new javax.swing.JButton();
        btn_cancel1 = new javax.swing.JButton();
        txt_c_user = new javax.swing.JTextField();
        lbl_m_user = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_psswd = new javax.swing.JLabel();
        txt_psswd = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_inst = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add);
        btn_add.setBounds(580, 150, 150, 60);

        btn_cancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btn_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel1);
        btn_cancel1.setBounds(580, 210, 150, 60);
        getContentPane().add(txt_c_user);
        txt_c_user.setBounds(340, 190, 170, 24);

        lbl_m_user.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_m_user.setForeground(new java.awt.Color(204, 255, 255));
        lbl_m_user.setText("Enter a username:");
        getContentPane().add(lbl_m_user);
        lbl_m_user.setBounds(170, 190, 150, 30);

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username);
        txt_username.setBounds(440, 170, 73, 24);

        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Username");
        getContentPane().add(lbl_username);
        lbl_username.setBounds(330, 170, 59, 16);

        lbl_psswd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_psswd.setText("password");
        getContentPane().add(lbl_psswd);
        lbl_psswd.setBounds(330, 210, 57, 16);

        txt_psswd.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txt_psswdComponentShown(evt);
            }
        });
        txt_psswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_psswdActionPerformed(evt);
            }
        });
        getContentPane().add(txt_psswd);
        txt_psswd.setBounds(440, 210, 73, 24);

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(270, 250, 150, 60);

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel);
        btn_cancel.setBounds(430, 250, 160, 60);

        lbl_inst.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_inst.setForeground(new java.awt.Color(204, 255, 255));
        lbl_inst.setText("create an user name here to play the game :");
        getContentPane().add(lbl_inst);
        lbl_inst.setBounds(240, 100, 400, 25);

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backm.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(350, 250, 150, 60);

        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admin);
        btn_admin.setBounds(350, 130, 150, 60);

        btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/player.png"))); // NOI18N
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });
        getContentPane().add(btn_user);
        btn_user.setBounds(350, 190, 150, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_img.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -20, 800, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed

        usrcheck = txt_username.getText();


    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        txt_username.setText("");
        txt_psswd.setText("");
        btn_login.setEnabled(false);
        resources r = new resources();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_psswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_psswdActionPerformed

        usrcheck = txt_username.getText();
        passcheck = txt_psswd.getText();
        if (usrcheck.equals("admin")) {
            if (passcheck.equals("admin")) {
                System.out.print("allowed");
                btn_login.setEnabled(true);

            }
        } else {
            System.out.print("denied");
        }
    }//GEN-LAST:event_txt_psswdActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed

        btn_back.setVisible(true);
        lbl_username.setVisible(false);
        txt_username.setVisible(false);
        lbl_psswd.setVisible(false);
        txt_psswd.setVisible(false);
        btn_login.setVisible(false);
        btn_cancel.setVisible(false);
        btn_admin.setVisible(true);
        btn_user.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed

        btn_back.setVisible(false);
        btn_admin.setVisible(false);
        btn_user.setVisible(false);
        lbl_username.setVisible(true);
        txt_username.setVisible(true);
        lbl_psswd.setVisible(true);
        txt_psswd.setVisible(true);
        btn_login.setVisible(true);
        btn_cancel.setVisible(true);

    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        lbl_inst.setVisible(true);
        btn_back.setVisible(false);
        btn_admin.setVisible(false);
        btn_user.setVisible(false);
        lbl_m_user.setVisible(true);
        txt_c_user.setVisible(true);
        btn_add.setVisible(true);
        btn_cancel1.setVisible(true);
    }//GEN-LAST:event_btn_userActionPerformed

    private void btn_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel1ActionPerformed
        lbl_inst.setVisible(false);
        btn_back.setVisible(true);
        lbl_m_user.setVisible(false);
        txt_c_user.setVisible(false);
        btn_add.setVisible(false);
        btn_cancel1.setVisible(false);
        btn_admin.setVisible(true);
        btn_user.setVisible(true);
    }//GEN-LAST:event_btn_cancel1ActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        
        username = txt_c_user.getText();
        String insert = "insert into tbl_player(player_name) values('" + username + "')";
        int a = obj.ExecuteQuery(insert);
        JOptionPane.showMessageDialog(this, "Username created!!!");
        hangman h = new hangman();
        h.setVisible(true);
        h.query();
        this.setVisible(false);
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_psswdComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txt_psswdComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_psswdComponentShown

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        Mainmenu m = new Mainmenu();
        m.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cancel1;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel lbl_inst;
    private javax.swing.JLabel lbl_m_user;
    private javax.swing.JLabel lbl_psswd;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txt_c_user;
    private javax.swing.JTextField txt_psswd;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
